#cloud-config
package_update: true

runcmd:
  - hostnamectl set-hostname ${hostname}
  - grep -q "$(hostname)" /etc/hosts || echo "127.0.0.1 $(hostname)" >> /etc/hosts
  - mkdir -p /etc/rancher/rke2
  - |
    TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" || true)
    PUBLIC_IP=$(curl -s -f -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4 || echo "127.0.0.1")

    cat <<EOT > /etc/rancher/rke2/config.yaml
    server: https://${server_private_ip}:9345
    token: "${rke2_token}"
    node-external-ip:
      - "$PUBLIC_IP"
    node-label:
      - "node.kubernetes.io/instance-type=gpu"
      - "accelerator=nvidia-gpu"
    EOT

  - curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION="${rke2_version}" INSTALL_RKE2_TYPE="agent" sh -
  - systemctl enable rke2-agent.service
  - systemctl start rke2-agent.servicea
